'use client'
import React, { useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';

export default function Page() {
    const [openIndex, setOpenIndex] = useState(0);
    const contentRefs = useRef([]);

    const toggle = (index) => {
        setOpenIndex(openIndex === index ? null : index);
    };
    const policySections = [{
        title: 'Subscription Contract and Acceptance',
        content: (<> <p className="mb-2"><strong>Subscription Contract.</strong> These terms of service, as amended/modified from time to time, the CAF, the Privacy Policy and/or the offers and conditions on the Company Website, shall collectively be referred to as, the “Contract”. By executing the CAF and/or by using the Services and/or by using any of the services or products provided by the Company in connection with the Services, the Subscriber signifies that he/she has read, understood and accepted the terms and conditions mentioned in the Contract. </p>
                        <p>The Subscriber shall not use the services as an ‘OSP’ (other service provider) or for the purposes of telemarketing, directly or indirectly, without submitting to the Company, the required registration/ license from relevant authorities. The Subscriber shall not indulge in UCC. UCC refers to Unsolicited Commercial Communications (UCC), any commercial communication that is neither as per the consent given by recipient to sender of commercial communication nor as per registered preference(s) of recipient. The Subscriber shall be solely responsible for same and Company shall be entitled take appropriate action.</p>
                        <p><strong>Customer Application Form (CAF).</strong> The Subscriber must provide accurate and complete information on the CAF together with supporting documents, including, without limitation, valid proof of address and identity and such other documents that may be mandated under law. Identification proof must include photo  identification proof, e.g., aadhar card, voter identification card, ration card, passport or drivers license. Company will not be liable for any incorrect information and/or document provided by the Subscriber, whether obtained illegally, or by means of fraud or forgery, or otherwise. The Company reserves the right to reject, in whole or in part, and without any liability whatsoever, any CAF without assigning any reason, including rejecting the CAF for incomplete or incorrect information/documents. The Company reserves the right to visit the Subscriber to conduct a verification.</p>
                        <p><strong>Heirs and Permitted Assigns.</strong> The Contract binds the Subscriber, his heirs, executors, administrators, successors, and permitted assigns, and the Company and its successors and assigns.</p>
                        <p><strong>Amendment/Modification.</strong> Company, in its sole discretion, reserves the right to modify or revise the Contract, at any time. The Subscriber agrees to be bound by such modifications or revisions. Nothing in the Contract shall be deemed to confer any third-party rights or benefits. The Subscriber should periodically review the Company Website for the up-to-date version of these terms of services and other policies forming part of the Contract.</p>
                        <p><strong>Term.    </strong> The Contract will commence upon execution of the CAF and will remain valid, subject to applicable terms and conditions.</p>
        </>)
    }, {
        title: 'Services',
        content: (<><p className="mb-2"><strong>Fixed Broadband Service.</strong> The Service is available only in India. The service shall be provided within a reasonable time of receipt and acceptance of CAF by the Company and subject to technical feasibility. The Company grants the Subscriber permission to use the Company’s Fixed Broadband Service, subject to payment of the Subscription Fee. The Fixed Broadband Service must only be used within the location registered with the Company as the Installation Address and only for one connection. Additional connections will require an additional setup or registration as outlined below.  </p>
                        <p>Encryption and Records. Subscriber must not employ bulk encryption. The use of encryption by the Subscriber will be governed by the Information Technology Act, 2000. The Company shall maintain a log of all users connected and the services they are using (mail, telnet http, etc.). Subscriber must also log every outward login or telnet through their computers. These logs, together with copies of all the packets originating from the Broadband Router, must be made available by the Subscriber in REAL TIME to the Company and/or the relevant authorities. Type of logins where the identity of the logged-in user is not known, should not be permitted.</p>
                        <p><strong>Encryption and Records.</strong> Subscriber must not employ bulk encryption. The use of encryption by the Subscriber will be governed by the Information Technology Act, 2000. The Company shall maintain a log of all users connected and the services they are using (mail, telnet http, etc.). Subscriber must also log every outward login or telnet through their computers. These logs, together with copies of all the packets originating from the Broadband Router, must be made available by the Subscriber in REAL TIME to the Company and/or the relevant authorities. Type of logins where the identity of the logged-in user is not known, should not be permitted.</p>
                        <p><strong>Interruption of Services,</strong> blocking of internet. Company shall use reasonable endeavours to maintain the maximum possible uptime of the Services, as mandated under law, however, the Company cannot guarantee that the Services will be fault free without any interruption, disruption or downtime. Company may suspend the Services: (i) in order to carry out maintenance or testing; (ii) to safeguard the security and integrity of the Services or for technical purposes; or (iii) if so directed by the government. Company may, from time to time, block internet sites and/or any individual Subscriber, as identified and directed by an enforcement agency, including DoT. Company shall not be liable to refund any amounts to the Subscriber nor compensate the Subscriber for any such disruption of Services, internet downtime or for any of the above reasons.</p>
                        <p><strong>Quality, functionality, and/or availability of the services.</strong> Quality, functionality, and/or availability of the Services may be affected and the Company, without any liability whatsoever, is entitled to refuse, limit, suspend, vary or disconnect the Services at any time, for any reasonable cause, in line with the existing licenses and regulations, including, but not limited to, the following:</p>
                        <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ul className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 15px" }}>
                                <li>Any violation of applicable rules, regulations, orders, directions, notifications, conditions of the License Agreement, etc., issued by Government/ DoT/TRAI, or any other law for the time being in force;</li>
                                <li>Any discrepancy in the particular(s) provided by the Subscriber in the CAF;</li>
                                <li>If the Subscriber defaults in making a payment (including past defaults) for the Services or for any other charges due to the Company;</li>
                                <li>During technical failure, modification, up-gradation, variation, relocation, repair and/or maintenance of the systems/equipment;</li>
                                <li>To combat potential fraud, sabotage, wilful destruction or threat to national security;</li>
                                <li>Transmission limitation caused by topographical, geographical, atmospheric, hydrological and/or mechanical or electronic constraints/limitations and/or due to non-availability of suitable technical sites to install/upgrade the network;</li>
                                <li>Due to force majeure such as acts of God or circumstances beyond the control of the Company, including, insurrection, civil disorder or military operations, national or local emergency, industrial disputes of any kind (whether or not involving the Company), fire, lightening, explosion, flood, inclement weather conditions, acts of or commission by persons or bodies for whom the Company is not responsible or any Act, Regulations or Policy of the Government of India or State Government or any other Statutory Authority, etc.;</li>
                                <li>If the Services are used in violation of any law, rule or regulation, or for a purpose other than that declared by the Subscriber at the time of subscription;</li>
                                <li>Interconnection failure between the Company and other service provider(s);</li>
                                <li>Any bonafide action taken by the Company to protect its Intellectual Property Rights (IPR) or such rights of the content providers or any other person, whose interest the Company is bound to protect under contract or law;</li>
                                <li>Any other reason, which the Company finds as reasonable warranting a limitation/ disconnection of the Services.</li>
                            </ul>
                        </div>
        </>)
    }, {
        title: 'Subscriber Account and Activation Services',
        content: (<><p className="mb-2"><strong>Creation and Activation.</strong> Company shall create a Subscriber Account and activate the Fixed Broadband Service only upon (i) receipt of all payments from the Subscriber, including the Subscription Fee; (ii) successful completion of the Installation Service; (iii) submission of duly filled and signed CAF in legible writing; and (iv) submission of all documents by the Subscriber to the satisfaction of the Company. The Subscriber must pay all the Activation Charges and/or Subscription Fee through (i) an authorized dealer of the Company; (ii) the option of online payment available on the Company’s Website, or (iii) using any other payment method, as may be notified to the Subscriber by the Company. The Subscriber shall always provide the Company with accurate, current and complete information of the Subscriber, including in the CAF. The Subscriber shall promptly inform the Company about any change in such information.</p>
                        <p><strong>Subscriber Account and Security.</strong> Upon creation of the Subscriber Account, the Subscriber shall be allotted a Subscriber ID. Subscriber must not share the Subscriber ID with any third party and shall keep the Subscriber ID safe and secure. Company reserves the right to issue a new Subscriber Account or Subscriber ID to the Subscriber from time to time. Subscriber is solely responsible for the activity that occurs on the Subscriber Account and must immediately notify the Company of any breach of security or unauthorized use of the Subscriber Account or Subscriber ID. The Company will not be liable for any losses incurred by the Subscriber due to any unauthorized use Subscriber will be liable for all losses incurred by the Company or others due to such unauthorized use.</p>
                        <p><strong>Transactions.</strong> Subscriber may transact either online by visiting the Company Website, calling the Helpline or by using the short messaging facility (if any) or missed call facility (if any) provided by the Company. No financial transaction will be processed by the Company if the Subscriber or any of its Authorised Representatives fails to provide all relevant and correct details as requested by the Company, including details to verify the authenticity of the Subscriber/ Authorised Representative (as the case may be). The Company, from time to time, may introduce alternative options to access and transact under the Subscriber Account. The Company reserves the right to withdraw any of the options at any time without prior notice to the Subscriber. The Registered Mobile Number of the Subscriber will be the primary number throughout the Term and the Subscriber shall continue to receive all (a) payment reminder or confirmation messages; (b) confirmations of transactions in connection with the Subscriber Account; and (c) other promotional or service related messages, Whats App messages and transactions in connection with the Subscriber Account. Upon providing the Registered Mobile Number, the Subscriber shall deem to have consented to receive such messages and Whats App messages from Company.</p>
                        <p><strong>Helpline.</strong>Helpline. Calls by the Subscriber or the Authorized Representative from Registered Mobile Numbers will be identified by the Helpline. The Company reserves the right to ask questions to verify the identity of the caller. If calls are made from an unregistered number, the Company may seek verification details in accordance with a verification process. Upon identification of the Subscriber Number, the Subscriber may be given an option to de-register the existing number and replace it with the new number. The Company reserves the right to monitor and record the calls made by the Subscriber to the Company.</p>
                        <p><strong>Authorised Representative.</strong> The Subscriber, at its sole discretion and risk, may share the Subscriber ID with its Authorised Representative. The Authorised Representative must meet the Eligibility Criteria mentioned above in Clause 2. The Subscriber acknowledges and agrees that by taking any actions or allowing any actions to be taken on behalf of the Subscriber by the Authorised Representative, including without limitation, selecting a Package, accepting the Service and signing the CAF, the Subscriber accepts to be bound by the terms and conditions of this Subscription Contract.</p>
        </>)
    }, {
        title: 'Setup, Installation and Relocation',
        content: (<><p className="mb-2">Suitable Broadband Router. Subscriber must have a suitable Broadband Router in order to facilitate the provision of and use of the Fixed Broadband Service. Subscriber shall be solely responsible for ensuring that the Broadband Router used by the Subscriber is compatible with the Fixed Broadband Service. Subscriber shall ensure that the Broadband Router meets the system requirements of the Company. Company does not warrant or accept any responsibility (legal, technical or otherwise) for operation of the Broadband Router used to access the Fixed Broadband Services of the Company or use of the Broadband Router or in conjunction with Company Hardware that may be provided to facilitate provision of the Fixed Broadband Service. The Subscriber shall provide the Company with reasonable access to the Broadband Router.</p>
                        <p>Incidental Accessories and services. The Subscriber shall be solely responsible to ensure compatibility of the Incidental Accessories and services with the Company Hardware, the Broadband Router and/or the Fixed Broadband Service. The Subscriber shall ensure that the Incidental Accessories and services meet the system requirements of the Company and/or the Company Hardware and/or the Broadband Router. The Company does not warrant or accept any responsibility for operation of the Incidental Accessories and services.</p>
                        <p>WIFi Device. If the Subscriber is interested in using the Fixed Broadband Service through a WIFi Device such as router or access point, the Subscriber must inform the Company of such installation and usage are governed by specific guidelines laid down by the DoT. If the Subscriber uses the Fixed Broadband Service through WiFi Devices, the subscriber should:</p>
                        <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ul className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 40px" }}>
                                <li>Setup and maintain its own password mechanism for its internet usage / Wi-Fi Services.</li>
                                <li>Ensure that the network including the Fixed Broadband Service is not misused.</li>
                                <li>Be solely responsible to comply with all the laws including the guidelines as prescribed by the DoT via circular no. 820-1/2008-DS Pt-II dated 23rd Feb. 2009.</li>
                                <li>Keep log of all the events on Wi-Fi network for a period of at least one year and shall provide the  same to the Company, the regulator and/or security agencies as and when demanded.</li>
                                <li>Any Subscriber who deploys a wifi router in the Installation Address shall be activated only after it is registered for centralized authentication with the Company.</li>
                            </ul>
                        </div>
        </>)
    }, {
        title: 'Inability to Activate',
        content: (<> <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ul className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 40px" }}>
                                <li>Company shall not be responsible, in any manner whatsoever, under the Contract if the Activation has not been performed or completed or cannot be performed, because (i) necessary permissions or authorisations have not been obtained or are withdrawn; (ii) the Subscriber has failed to furnish any information or documents as may be required by the Company; (iii) of reasons attributable to the Subscriber, including, non-availability of Broadband Router or third-party services, such as, Incidental Accessories and services, e.g. electrician;   or (v) of  any  force majeure event.</li>
                                <li>Activation of the Fixed Broadband Service require vital activities and time, including, feasibility check of the area, laying down of cables, proper wiring of the area/premises, allocation of tag in the switch, configuration of the Broadband Router or other technical requirements, etc. The Company does not guarantee the provision of services or prescribe any fixed timeline within which such services will be activated after execution of the CAF.  Subscriber shall only be entitled to a refund of the initial amount paid by the Subscriber.</li>
                            </ul>
                            <p>Relocation of Services. The Company allows its Subscriber to change the Address of provision of the Fixed Broadband Services to another residence, office or location of the Subscriber within the selected geographical area or locations where the Services are provided by the Company. If the Subscriber is interested to change the Address, the Subscriber must inform the Company by contacting the Helpline and booking a Relocation Work Order by giving the Helpline details of the new Address. Subscriber will be informed about the procedure and the applicable charges, as fixed by the Company, from time to time. Company shall not refund any amount to the Subscriber if he/she wishes to relocate or shift to locations where the Services are not provided by the Company. Additionally, the Company does not guarantee that the Fixed Broadband Service can be provided at the new Address or that the Subscriber will receive the Fixed Broadband Service at the new Address, even if such Services are provided in that location and/or area. Installation at the new Address will be subject to the terms and conditions applicable in connection with the Installation Services, including submission of valid proof of the new Address and/or such other information and document that may be required by the Company.</p>
                        </div>
        </>)
    }, {
        title: 'Tariff, Subscription Fees, Other Charges and Payments',
        content: (<><p><strong>Prices and Applicable Taxes.</strong> Tariff, Activation Charges, Subscription Fees or other charges shall be payable by the Subscriber in accordance with the tariff plans and associated offers that may be introduced by the Company from time to time in accordance with applicable law. The Company reserves the right, without any previous notification to the Subscriber, to change the prices, including increase the prices or modify the plan and offer. Subscriber must visit the Company Website for the updated prices, tariff plans and offers. Subscriber shall be entitled to only those discounts, credits or refunds as expressly authorised by the Company. Subscriber shall maintain a security deposit, if required in accordance with the terms of the package or the offer that may be subscribed by the Subscriber. The Company reserves the right to forfeit/adjust/apply the said security deposit in full or in part satisfaction of any sum due from the Subscriber to the Company at any time. Unless otherwise specified by the Company, the Subscriber is solely responsible and liable for payment of all applicable taxes, duties, levies and charges imposed by or under any applicable law in connection with the Fixed Broadband Service or any associated services.</p>
                        <p><strong>Payments.</strong> All Services under the Contract are pre-paid services and therefore, the Subscriber must pay all fees and/or charges including Subscription Fee to the Company before availing any Services from the Company. In addition to the Subscription Fee, the Company reserves the right to charge the Subscriber additional amounts, including for Relocation Services, repair services, or such other offers, packages and additional services provided or associated with the Fixed Broadband Services. All transactions between the Company and the Subscriber shall be done through the Subscriber Account. Account Balance in the Subscriber Account is non-transferable and non-refundable. The Subscriber shall pay all dues in full, without any deduction, set-off or withholding in respect of the Services provided by the Company, including internet services or services in connection with the Subscriber Account, whether or not authorised by the Subscriber and whether or not these dues exceed the assigned credit limit (if any). Acceptance of payment from a person other than the Subscriber will not amount to the Company having transferred or subrogated any of the rights or obligations of the Subscriber to such third party.</p>
                        <p><strong>Account Statement.</strong> Subscriber will be sent an Account Statement on a periodic basis. The Account Statement will be sent by email to the registered email address of the Subscriber. It shall be the responsibility of the Subscriber to ensure that the Company has the correct and latest email address. The Account Statement will contain details of the transactions made between the Subscriber and the Company in the previous month in connection with the Subscriber Account. Account Statements for the previous six months can be accessed by the Subscriber, free of cost, on the Company Website. Subscriber may request copies of the Account Statement for the previous month, which may be provided by the Company via e-mail to the registered email address. The Company reserves the right to charge additional amount for such additional services and debit the amount from the Subscriber Account.</p>
                        <p><strong>Due Date and Non-payment.</strong> All payments shall be made in full by the due date. Any delay in payment beyond the due date will result in suspension or disconnection of the service as deemed fit by the Company. All payment made by cheques and other non-cash payments are subject to realization. In case the cheque issued by the Subscriber is dishonoured or returned by the relevant bank for any reason, including insufficient funds, Subscriber shall be liable to pay such charges as may be levied by the Company, without prejudice to the other rights that the Company may have under law for recovery of monies and dishonour of cheques. In case any services provided by the Company are post-paid, any non-payment of fees and charges before the due date shall attract interest at 18% per annum or the maximum rate permitted by law. All foregoing rights of the Company for recovery of dues from the Subscriber shall be without prejudice to other rights that the Company may have under law or under the Subscription Contract including, without limitation, deactivation and cancellation of the Services.</p>
                        <p><strong>Dispute regarding Account Statement /Charges.</strong> In case of any disputes(s) regarding the charge(s) levied, the Subscriber shall notify the Company in writing within seven (7) days of receipt of the Account Statement and/or notification from the Company, failing which, such Account Statement and/or notification from the Company shall be considered as undisputed. Subscriber shall also pay full amount of disputed charges, if any, irrespective of any pending dispute(s). No waiver by the Company to the Subscriber shall, in any event, become effective unless the same is in writing and such waiver shall be effective for the limited and specific instance for which it is given.</p>
        </>)
    }, {
        title: 'Offer, Discounts, Packages and Package Migration',
        content: (<><p><strong>Services, additional or supplementary Services.</strong> Company is entitled to add/alter or withdraw any additional or supplementary Services, including, the charges for the same, at any time, in its sole direction, in accordance with DoT/ TRAI guidelines. Provision of additional/supplementary Services shall be on such other/additional terms and conditions as specified by the Company from time to time and such other/additional terms and conditions shall be deemed to be a part and parcel of the Contract.</p>
                        <p><strong>Packages and Offer. </strong>Subscriber must subscribe to any one of the Primary Packages offered by the Company. In addition to the Primary Packages, the Subscriber may subscribe to Add-On Packs or such other associated services as may be introduced by the Company from time to time. The details of such packages and associated services shall be published on the Company Website. Company is constantly evolving in order to provide the best possible experience and information to its subscribers. Consequently, different plans, schemes, top ups, and/or packages offered by the Company shall have correspondingly different compositions, prices, charges, fees and terms and conditions applicable to them, all of which are subject to change by the Company from time to time, in line with the overall regulatory guidelines. The Company reserves the rights to change, replace, modify suspend, cancel or discontinue any or all Primary Packages, Add-On Packs or associated services at any time without notice, in accordance with applicable law and the Subscriber must visit the Company Website for the latest information in this regard.</p>
                        <p><strong>Package Migration</strong> Subscriber may, at any time, request to change the Package subscribed by the Subscriber. The Subscriber will be liable to pay the applicable charges for the requested Package and such charges shall be payable before availing the new Package. In case of change of Plan by Subscriber during any existing broadband plan, the Company at its own discretion reserves the right to forfeit/ adjust/ apply the balance validity period or data or amount of the previous plan of the Subscriber in full or in part.</p>
                        <p><strong>Discounts and Special Benefits Schemes.</strong> Company may announce discounts or other special benefit schemes pertaining to the Service and/or additional/supplementary and withdraw/vary/extend such schemes at its sole discretion without incurring any liability whatsoever.</p>
        </>)
    }, {
        title: 'Incidental Accessories and Services',
        content: (<><p><strong>Incidental Accessories and services including Power Supply.</strong> Subscriber is solely responsible to supply the Incidental Accessories and services, including power supply. In order to receive an uninterrupted Fixed Broadband Service, the Subscriber must never switch off the power to the Broadband Router. Company will not be liable if any Incidental Accessories and/or services are faulty or incompatible and the loss or inability to use Incidental Accessories and/or services shall not absolve the Subscriber from the Subscriber’s liability to pay charges on account of the Fixed Broadband Service.</p>
                        <p><strong>Maintenance. </strong> The Company shall not be responsible for the maintenance of the Company Hardware. The Subscriber must maintain and keep the Company Hardware in good and useable condition at all times (normal wear and tear excepted), until returned to or collected by the Company. Company Hardware cannot be moved from the Installation Address without the prior written approval of the Company. The Company alone is authorised to install, retrieve or repair the Company Hardware. The Subscriber must keep the Company Hardware safely and must not remove any marking that identifies the Company Hardware as belonging to the Company. Subscriber must not allow the Company Hardware to be tampered with or otherwise used in any manner not specifically authorised by the Company.</p>
                        <p><strong>Warranty</strong> Warranty Services supplied by the Company are on ‘As is and Available’ basis only. Company does not warranty that the services will be uninterrupted, error-free or free from viruses, Trojan horses or harmful components. Subscriber is solely responsible to evaluate the accuracy, completeness and usefulness of all services, products and other information and the quality and merchantability of all the merchandise. Company is not the manufacturer of any Company Hardware and does not give any independent warranty to the Subscriber for such equipment. The manufacturer may or may not have provided a warranty in relation to the Company Hardware. If a warranty is given by the manufacturer, the Subscriber shall follow all the terms and conditions stated in such warranties and in case of redeeming the warranty, the Subscriber shall directly approach such manufacturer without making any claims against the Company for any non-compliance of the warranty by the manufacturer.</p>
                        <p><strong>Prohibited use of Services and Internet Telephony.</strong> Company forbids its Subscriber to use the Fixed Broadband Services or Company Hardware to transmit any objectionable or obscene messages or communication, which is inconsistent with applicable laws or religious norms, or for using any malicious, illegal, abusive, threatening or harassing messages to generate spam traffic, anti-national or immoral activities, including, without limitation, illegal voice termination activities or that results in damaging or risking the Company or its Network/equipments/call center and/or other subscribers. Use of the Fixed Broadband Services or the Company Hardware for establishing voice communication using PSTN / PLMN, reselling or offering to sell services similar to these or interconnectivity to other internet service providers is completely prohibited. Any detection of such prohibited uses will invite immediate censure by the Company and such actions shall be reported to the relevant authorities. Any breach of this section or violation of the law will result in immediate action by the Company, including initiating legal proceedings or filing a complaint with the relevant authorities for the purposes of enforcement of any legal remedy or action. Any violation or misuse by any Subscriber shall under no circumstances be attributable to the Company and the Subscriber shall be solely responsible for all such acts or omissions.</p>
                        <p>In furtherance to this intent, Company, with or without notification to the Subscriber, may deploy security measures to detect piracy or any unlawful activity that may be conducted by use of the Fixed Broadband Services provided by the Company. These security measures could include fingerprinting mechanism and monitoring of all activities connected to the service including usage of the Fixed Broadband Services under the Contract. Company reserves the right to enter into the premises to inspect and audit the premises without any prior notification to the Subscriber. Company has the right to immediately deactivate, cancel and terminate the Contract, the Subscriber Account and take the possession of the Company Hardware including any connected devices, information or documents. The foregoing rights are in addition to all the other rights that the Company may have under the law, including initiating proceedings including legal proceedings and sharing of information with the enforcement agencies.</p>
                        <p><strong>Inspection, Suspension and Repossession.</strong> Company, without any prior notification and during reasonable hours permitted under the law any time during the Term of the Contract, may enter the Installation Address to inspect and verify if the Subscriber is in compliance with the Subscription Contract. Company shall be entitled to take photographs and collect documents, materials, equipment or other information necessary as proof of any violation of the Contract or intellectual property rights of any party.</p>
        </>)
    }, {
        title: 'Subscriber Obligations',
        content: (<> <p>Subscriber shall not use the Services for any unlawful or immoral purposes including that which are in violation or derogation of any law or for any purposes which are against any public policy or for sending/receiving obscene, threatening, harassing messages/ communications or sending messages or communications that affect national interest, or result in damaging or risking the Company or its Network/equipments/call center and/or other subscriber(s). The Subscriber shall be solely responsible for all such acts or omissions.</p>
                        <p>The Subscriber shall not use the services as an ‘OSP’ (other service provider) or for the purposes of telemarketing, directly or indirectly, without submitting to the Company, the required registration/ license from relevant authorities.</p>
                        <p>Unless specifically allowed by the Company, the Subscriber shall not change the configuration of its EPBAX set during installation or at any time subsequent thereto pursuant to which any of the under mentioned possibilities could arise:</p>
                        <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ul className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 40px" }}>
                                <li>Any setting in the EPBAX resulting in only the Pilot number being transmitted irrespective of the extension (Directory Number) from which the call is originating;</li>
                                <li>Any setting in the EPBAX resulting in incomplete extension (Directory Number) being displayed, thereby meaning that a lesser number of digits are either allotted or displayed;</li>
                                <li>Subscriber shall provide a certificate from the EPBAX Equipment Vendor (whenever specially sought by the Company) that the software has not been tampered with, in violation of the National Numbering Plan specified by DoT.</li>
                                <li>In case the Subscriber wishes to use the EPBAX with a private network and PSTN, they must have appropriate authorization from DoT and it must be ensured that the separation of traffic is done through logical partitioning.</li>
                            </ul>
                        </div>
        </>)
    }, {
        title: 'Subscriber Undertakings',
        content: (<> <p>The Subscriber acknowledges, agrees, and undertakes:</p>
                        <p>That the documents/details submitted by the Subscriber along with the CAF are subject to clearance/acceptance by the Company. In case of non-acceptance/rejections of documents, the refund, wherever applicable, will be made as per DOT or TRAI regulations, as may be amended from time to time.</p>
                        <p>To pay to the Company the Subscription Fee including the tariff charges as published and notified by Company from time to time.</p>
                        <p>That the Subscriber is fully conversant with the Services provided by the Company together with its charges, specification, requirements, limitations, etc., and has signed the Contract with complete understanding of the terms and conditions and of the obligations of the Subscriber.</p>
                        <p>That the provisions of the Indian Telegraph Act 1885 and rules made thereunder (including amendments thereto and rules framed thereunder, from time to time) shall be applicable to each and every Subscriber.</p>
                        <p>To comply with all applicable laws, including rules, regulations, orders, directions, notifications, etc., of the Government/Court/tribunals/TRAI/DoT/TERM Cells and shall also comply with all the directions issued by the Company related to the network, service, equipment, or connected matters and shall provide to the Company all information and cooperation as may be required by the Company from time to time.</p>
                        <p><strong>Acceptance of Terms and Conditions:</strong></p>
                        <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ol className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 40px" }}>
                                <li>I agree to allow Tata Play Broadband Pvt. Ltd. (TPBB) or Tata Play Fiber (TPF) sales representative to click my live photo and the photo of POA/POI for the issuance of Broadband Services.</li>
                                <li>I hereby declare that the information shared by me is true and correct.</li>
                                <li>I hereby confirm that I have read and understood all the terms and conditions mentioned online on the TPBB site and I agree to the same.</li>
                                <li>The consent code entered by me can be treated as my signature.</li>
                                <li>I’d like to receive alerts and messages from Tata Play Broadband Pvt. Ltd. via WhatsApp related to my account.</li>
                            </ol>
                        </div>
        </>)
    }, {
        title: 'Termination, deactivation, and reactivation',
        content: (<><p><strong>Deactivation.</strong> Company reserves the right to deactivate the Subscriber Account for any reason, including Subscriber’s failure to comply with the Contract, non-payment or making unauthorised use of the Services, conducting piracy through the Services or if mandated by law, TRAI or DOT. In addition to the deactivation, the Company shall have the right to exercise all other rights and remedies that the Company may have under the law.</p>
                        <p><strong>Suspension.</strong> Company reserves the right, without notice or any liability whatsoever to the Subscriber, to interrupt, suspend, cancel, modify, or terminate any services supplied to the Subscriber, if such action is deemed necessary by the Company (i) under any law or is requested by any competent authority; (ii) for technical, maintenance, security or failure or degradation of any facilities, equipment or systems used to provide the Service; (iii) to combat any acts of piracy, fraud or misuse of the Service; (iv) due to any act beyond the control of the Company; (v) for any legitimate business purpose; or (vi) for reasons of threat to national interest, or in the event of emergency, such as, war or similar situation or if the services or content is anti- national, promotes political / religious propaganda, against public policy, banned or restricted from being distributed under any applicable laws or the Company otherwise determines that it is objectionable or obscene or derogatory to any person or class of persons or hurts the religious sentiments of any religious group or infringes the privacy rights of any individual or is not in the interest of subscribers or the general public. In the event of an interruption, suspension or deactivation of the Service, the Company may, at its discretion, reactivate the Service, subject to any conditions that the Company may impose from time to time.</p>
                        <p><strong>Cancellation.</strong> Subscriber may cancel or completely discontinue availing the Services by contacting the Company. In case of a cancellation or complete discontinuation of the Service, the Subscription Contract shall automatically stand terminated from the date of cancellation or discontinuation of that particular Services and Subscriber shall immediately return to the Company all the Company Hardware that the Subscriber may have in its possession.</p>
                        <p><strong>Reactivation.</strong> Company reserves the right to reactivate any suspended, cancelled or deactivated Subscriber Account at its sole discretion. Upon reactivation, the Company may deduct the expenses, charges and/or penalties that the Company may deem fit. These additional charges shall be debited from the Subscriber Account or separately recovered from the Subscriber at the option of the Company.</p>
                        <p><strong>Survival.</strong> Deactivation, suspension or termination shall be without prejudice to any other rights or remedies a party may be entitled to in law or under the Contract and shall not affect any accrued rights or liabilities of either Party nor the coming into force or the continuance in force of any provision of the Contract, which is expressly or by implication intended to come into or continue in force on or after such termination.</p>
        </>)
    }, {
        title: 'General Provisions',
        content: (<><p><strong>Intellectual Property Rights.</strong> Subscriber acknowledges and agrees that the Company Hardware, the associated equipment and services, signal, marks, logos embossed or associated with the forgoing and all copyrights, trademarks and other intellectual property rights in connection thereto are the exclusive property of the Company or the Company’s third party licensors and the Subscriber shall not do or permit anything to be done to infringe or violate such property rights or titles. The Subscriber shall immediately notify the Company if the Subscriber becomes aware of any unauthorised use of the whole or any part of the intellectual property rights of the Company, including, that related to the Company Hardware and the associated equipment and services.</p>
                        <p><strong>Privacy and Data Protection.</strong> Privacy of communication is subject to the terms of the Privacy Policy on the Company Website, the license agreement of the Company with DoT and other statutory and regulatory notifications/directives, etc. Subscriber grants its express consent to the Company to collect, use, share and/or retain the personal and sensitive personal information of the Subscriber and/or Authorized Representative, including all information shared by the Subscriber and/or Authorized Representative, and contact the Subscriber and/or Authorized Representative using their information for all purposes, including, fulfill the Subscriber’s or Authorized Representative’s requests regarding the Services, respond to their inquiries, conduct market research, enforce the legal terms, prevent fraud or potentially illegal activities, protect the safety of other subscribers, perform analyses, provide technical support, improving services, etc. The Company reserves the right to share information about the Subscriber (including personally identifiable information and viewing trends) with third parties for various purposes, including, (i) performing marketing, administration or other services including technical support; (ii) administering and processing requests; (iii) assisting in product development, research, strategic, financial or other business decisions; (iv) collecting patterns and conduct analysis, market research, analysis of group statistical patterns of the Subscribers to understand trends and patterns; (vi) obtaining professional advice including, enforcement of legal terms, prevention of fraud etc.; (vii) responding to proceedings (including legal, e.g., in response to a court order or a subpoena) or or disclosing information upon request of law enforcement agencies.</p>
                        <p><strong>Third Party Rights.</strong> The Subscriber shall not violate any third party rights or the privacy rights of any individual or entity. The Subscriber shall not make any public statement or media statement connected to the Company or its affiliate or group company or in relation to the services.</p>
                        <p><strong>Force Majeure.</strong> The Company will not be responsible or liable in any way for the failure or delay in the performance of its obligations due to Force Majeure. If a Force Majeure ceases to exist, the Company may perform or resume performance of its obligations and the time for performance will be extended by a period equal to the duration of the Force Majeure. Reasonable efforts shall be made to minimise such service disruptions. If Force Majeure persists, the Company will be entitled to terminate the Contract on written notice. The Subscriber shall remain liable for all charges during any such disruptions, unless decided otherwise by the Company.</p>
                        <p><strong>Disclaimer and Limitation of liability</strong></p>
                        <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ul className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 40px" }}>
                                <li>The Company makes no express or implied warranties, guarantees, representations or undertakings whatsoever regarding the Services/ equipment etc., unless expressly mentioned in the Contract. The Company specifically disclaims any statements indicating that the Company Hardware shall be without any fault or damage, including faults or damages resulting from exposure to adverse environmental conditions, including excessive moisture and excessive temperatures or damage to the Company Hardware on account of force majeure.</li>
                                <li>Subscriber availing any of the services supplied by the Company shall be at the sole risk, costs, charges and consequences of the Subscriber. Company, its affiliates, group companies, their officers, directors, employees, subcontractors, exclude all warranties, express or implied, in connection with the Services, including the use, accuracy, fitness for purpose, merchantability, completeness of the Services, suspension or cessation of the Services, any fraud, misrepresentation, negligence or loss that may be caused to the Subscriber or any third party in connection therewith. Company shall not be responsible for any deficiency in Services, delay and/or disruption in Services attributable, directly or indirectly, to the lines of upstream gateway services provider, damage to property or person that may take place during or in connection with any Installations, any loss incurred to the Subscriber or any third party resulting from the use of the Services or any omission or, consequential or indirect damages or losses . Regardless of the reasons, the liability of the Company will be limited to only proven direct damages or losses incurred by the Subscriber or any third party and the Company’s liability shall not exceed the Subscription Fee paid by the Subscriber for the Service in the six (6) months immediately preceding the specific event that gave rise to such damage or loss.</li>
                                <li>Company shall not be liable to the Subscriber and/or any person, firm, body corporate claiming through, under or in trust for the Subscriber and the Subscriber hereby waives all claims/actions of any delays or losses, including, but not limited to, loss of business, profit, revenue or goodwill demands fees, cost expenses, order judgment, etc. or any direct, incidental or consequential losses arising out of any delays, errors of defects, etc. Further, the Subscriber remains solely responsible for his/her negligence, acts or omissions.</li>
                                <li>Company shall not be responsible for any acts or omissions of direct sales agents, franchisees or any other third party with respect to schemes or benefits which are not authorized by the Company or which are purported to have been offered on behalf of the Company without the explicit and specific sanction in writing of the Company.</li>
                                <li>The DSL/Broadband speed available to the Subscriber is the maximum prescribed speed for which the Subscriber is entitled to and the Company does not hold out any assurance that the said speed shall be maintained at all times. Such speed may vary depending upon Network congestion, technical reasons or any other unavoidable circumstances.</li>
                                <li>Company will not incur any liability for any of its bonafide action taken to protect Intellectual property rights (IPR), including, anti-piracy actions, even if the information on the basis of which it has taken any action is later discovered to be unfounded or false.</li>
                                <li>Company is only a facilitator providing connectivity to the internet and has no responsibility or control over the contents of the internet or the usage. Subscriber understands the internet contains unedited material, some of which may be illegal, obscene, sexually explicit or pornographic that may be offensive to some people and access to such material will be at the sole risk of the Subscriber. Company is not responsible for any virus or malicious traffic which may infect the Broadband Router, including, personal computers, laptops and television screens.</li>
                            </ul>
                        </div>
                        <p><strong>Reservation. The Company reserves the right:</strong></p>
                        <div className="list-svg line-h-normal type-base rte-checkmark-att-blue">
                            <ul className="list-disc list-inside space-y-2 pl-4" style={{ "margin": "20px 40px" }}>
                                <li>To seek and/or verify the particulars, including financial information provided by the Subscriber, either by itself or from independent sources.</li>
                                <li>To reject any CAF in case the particulars provided therein are incomplete, incorrect or for any other valid reason and without any liability whatsoever. The information provided by the Subscriber / gathered by Company shall become Company property even if the application is rejected and the Company is not liable to return the same.</li>
                            </ul>
                        </div>
                        <p><strong>Indemnity.</strong> Subscriber agrees to defend, indemnify and hold harmless the Company, its parent company, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorneys fees) arising from the Subscribers use of and access to the Service, Subscribers violation of any term of the Contract or any third party right, including, without limitation, any copyright, property, or privacy right. The indemnification obligation will survive the termination of the Contract or the usage of the Services. The Subscriber agrees that where two or more persons constitute the Subscriber, their liability under this Subscription Contract including the CAF shall be joint and several.</p>
                        <p><strong>Headings.</strong> All headings are for convenience, and do not have any legal effect. Use of the singular includes the plural and vice versa.</p>
                        <p><strong>Assignment.</strong> The Contract cannot be transferred or assigned by the Subscriber, but may be delegated or assigned (in part or whole) by the Company to any third party without restriction.</p>
                        <p><strong>Relationship.</strong> The Contract is on a ‘principal to principal’ basis and the parties are independent of each other. N othing contained herein is intended to or shall be deemed to create any partnership, joint venture, employment or relationship of principal and agent between the parties or provides either with any right, power or authority, whether express or implied to create any such duty or obligation on behalf of the other party.</p>
                        <p><strong>Complete Terms; Severability.</strong> The Contract contains the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior agreements or understandings, written or oral, with respect to the subject matter. Every provision in the Contract is independent from the others to the extent that, if a provision, or any part of it, is ruled to be illegal or unenforceable that provision or the relevant part of it shall be treated as having been deleted from this Contract, without affecting the remainder of that provision or the other provisions of this Contract, which shall still have full effect except to the extent that Company’s rights/obligations under the Contract are materially impaired.</p>
                        <p><strong>Waiver.</strong> Neither Party shall lose any right under this Subscription Contract if it fails to use that right, or delays in using it. For a waiver of a right to be valid, it must be written and will not give rise to an ongoing waiver of that right unless it is expressly stated to do so.</p>
                        <p><strong>Confidentiality.</strong> Privacy of communication is subject to the terms of the license agreement of the Company with  DoT  and  other  statutory  and  regulatory  notifications/directives  and  agreements  with  the content providers, etc. The Subscriber specifically agrees that in order to facilitate the Company to provide Services, the Company may be required to disclose any information or particulars pertaining to the Subscriber to any authority, including, but not limited to, any debt collection agency, credit reference agency, security agency, and reserves the right to comply with the direction of such authorities at its discretion and without intimating the Subscriber.</p>
                        <p><strong>Notification, Complaints and Notices.</strong> All notifications, complaints and notices must be in writing and addressed to Customer Operations, Skyplay Private Limited, at its registered address or otherwise as specified by the Helpdesk. Any notification, complaints and notices given by the Subscriber shall be deemed to have been delivered to the Company when it is actually received by the Company. The Subscriber agrees that notifications provided by the Company in such Form as prescribed by the Company from time to time, including notifications provided by the Helpdesk, Alert, Account Statement or any other method specified by the Company or the Helpdesk, will be sufficient and adequate notice to the Subscriber.</p>
                        <p><strong>Arbitration.</strong> Any disputes and differences arising between the Subscriber and the Company will be referred to a sole Arbitrator to be appointed by Company. The provisions of Indian Arbitration and Conciliation Act, 1996 as amended from time to time would apply. The venue of arbitration shall be Chennai and the courts at chennai shall have exclusive jurisdiction in respect of all proceedings pertaining to the arbitration. All arbitration proceedings shall be in English language. The award passed by the arbitrator shall be final and binding upon the Parties.</p>
                        <p><strong>Governing Law and Jurisdiction.</strong> CAF and the Contract are governed by the laws of India. Subject to arbitration, courts in Chennai shall have exclusive jurisdiction over disputes arising from the Contract.</p>
                        <p><strong>Definitions.</strong> This section sets out specific meaning and explanation to few words for the ease of reference and understanding of the Subscriber.</p>
                        <p><strong>Company</strong> is Skylink Private Limited, a private company incorporated with limited liability under the Companies Act, 2013 bearing CIN U64204MH2015PTC267808 with its registered office at Office Nos.</p>
                        <p><strong>Subscriber</strong> is the person or the entity or the company named in the CAF, accepting these terms of services to avail the Fixed Broadband Service of the Company and/or availing the Fixed Broadband Services supplied in the Contract.</p>
                        <p><strong>Fixed Broadband Service</strong> is a type of high-speed internet access where connections to the internet are provided by cabling to the home or office or the location of the Subscribers.</p>
                        <p><strong>Broadband Router</strong> is the equipment obtained and used by the Subscriber to avail the Fixed Broadband Services supplied by the Company under the Contract.</p>
                        <p><strong>Company Hardware</strong> is the equipment and/or all accessories, which is under the full, legal and perpetual ownership and effective control of the Company and is supplied by the Company to the Subscriber on entrustment basis for the sole purpose of facilitating the Services including Active Fibre Optical Network and Subscriber Switch.</p>
                        <p><strong>CAF</strong> is the form signed by the Subscriber in connection with the Services availed of by the Subscriber.</p>
                        <p><strong>Installation Address</strong> is the location mentioned in the Company’s records, which is the home or office or the place of work /business of the Subscriber in India where the Fixed Broadband Service is installed by the Company.</p>
                        <p><strong>Address</strong> is the location of the home or office or the place of work/business of the Subscriber mentioned in India in the records of the Company and includes any new location(s) mentioned in the Company’s records as may be updated from time to time by the Subscriber in accordance with the Contract.</p>
                        <p><strong>Subscription Fees</strong> is the fee payable by the Subscriber to the Company for availing the Fixed Broadband Services of the Company and specifically excludes Activation Charges.</p>
                        <p><strong>Subscriber Account</strong> is the personal subscription account of the Subscriber with the Company for transactions with the Company.</p>
                        <p><strong>Subscriber ID</strong> is the unique subscriber identification code issued to the Subscriber for purposes of accessing the Subscriber Account.</p>
                        <p><strong>Helpline</strong> is the call centre which can be contacted at the telephone numbers published on the Company Website or otherwise informed to the Subscriber.</p>
                        <p><strong>Authorised Representative</strong> is a person of 18 years and above, competent under law and who is deemed to have been authorised by Subscriber to take actions under the Contract.</p>
                        <p><strong>Account Balance</strong> is the current available amount in the Subscriber Account.</p>
                        <p><strong>Activation Charges</strong> are charges collected under the terms of the Contract, for activation (or reactivation) of Fixed Broadband Service and include, whether charged separately or otherwise, wholly or partly, installation charges of the Fixed Broadband Service and any service charges, upgrade services but do not include Subscription Fee.</p>
                        <p><strong>Primary Package(s)</strong> is a package that a Subscriber must opt to avail the Fixed Broadband Service.</p>
                        <p><strong>Add-on Pack(s)</strong> is optional pack(s) that the Subscriber may or may not opt.</p>
                        <p><strong>Registered Mobile Number</strong> is the Indian mobile phone number of the Subscriber indicated in the Customer Application Form.</p>
                        <p><strong>DoT</strong> is Department of Telecommunications.</p>
                        <p><strong>Network</strong> is the Company’s telecommunication network in the service area through which services are or would be made available to the Subscriber.</p>
                        <p><strong>Services</strong> is all broadband and allied services provided by the Company to its Subscriber which, inter alia include Fixed Broadband Service, internet, and value added services and/or any supplementary/additional services made available to the Subscriber.</p>
                        <p><strong>TRAI</strong> refers to the Telecom Regulatory Authority of India.</p>
                        <p><strong>Tariff</strong> shall mean all the rates, fees, charges, levies etc. and related conditions at which the Services may be provided including, but not limited to, the Subscription Fee, activation or installation fees, usage charges, deposits, advances and service charges including applicable tax and any other statutory charge under the tariff schedule as notified by the Company for providing services and the tariff shall be in compliance with Tariff Telecommunication Orders issued by TRAI from time to time.</p>
        </>)
    },]
    return (
        <>
            <div className="w-full bg-gray-50">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
                    <div className="text-center">
                        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">Subscription
                            Contract</h1>
                        <p className="text-base md:text-lg text-gray-600 max-w-3xl mx-auto">Terms and conditions for
                            Skylink services.</p>
                    </div>
                </div>
            </div>

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
                <div
                    className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm overflow-hidden border border-gray-200 mb-8 p-6 md:p-8">
                    <div className="prose prose-sm md:prose max-w-none text-gray-700">
                        <p className="mb-4">The terms and conditions mentioned herein form part of the Customer
                            Application Form (CAF) signed by the Subscriber and are binding on the Subscriber.</p>
                        <p className="mb-4">Purpose Fixed Broadband Service is provided to the Subscriber by Skylink
                            Private Limited on the basis of the Contract (defined below), which governs the relationship
                            between the Company and the Subscriber while the Subscriber uses the Fixed Broadband
                            Services of the Company.</p>
                        <p className="mb-0">Eligibility (a) An individual residing in India, above 18 years of age,
                            fully competent under law to enter into the Contract or (b) a company/entity having its
                            place of business in India, represented by an individual having appropriate authority to
                            accept the Contract and sign the CAF.</p>
                    </div>
                </div>
                <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm overflow-hidden border border-gray-200">
                    {policySections.map(({title, content}, idx) => (
                        <div key={idx} className="border-b border-gray-200 last:border-b-0">
                            <h3 className="w-full">
                                <button
                                    onClick={() => toggle(idx)}
                                    className="w-full py-5 px-4 md:px-6 flex items-center justify-between text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 hover:bg-gray-50 transition-colors duration-200"
                                    aria-expanded={openIndex === idx}
                                    aria-controls={`section-content-${idx}`}
                                    id={`section-header-${idx}`}
                                >
                                    <span className="text-lg md:text-xl font-medium text-gray-900">{title}</span>
                                    <span
                                        className={`text-gray-500 transition-transform duration-300 ${openIndex === idx ? 'transform rotate-180' : ''}`}>
                                        {openIndex === idx ?
                                            <KeyboardArrowUpIcon className="h-6 w-6"/> :
                                            <KeyboardArrowDownIcon className="h-6 w-6"/>}
                                    </span>
                                </button>
                            </h3>
                            <AnimatePresence initial={false}>
                                {openIndex === idx && (
                                    <motion.div
                                        id={`section-content-${idx}`}
                                        role="region"
                                        aria-labelledby={`section-header-${idx}`}
                                        ref={(el) => (contentRefs.current[idx] = el)}
                                        className="px-4 md:px-6 overflow-hidden bg-white overflow-x-hidden"
                                        initial="collapsed"
                                        animate="open"
                                        exit="collapsed"
                                        variants={{
                                            open: {height: 'auto', opacity: 1, paddingTop: 16, paddingBottom: 24},
                                            collapsed: {height: 0, opacity: 0, paddingTop: 0, paddingBottom: 0},
                                        }}
                                        transition={{duration: 0.3, ease: 'easeInOut'}}
                                    >
                                        <div className="prose prose-sm md:prose max-w-none text-gray-700">
                                            {content}
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>
                        </div>
                    ))}
                </div>
            </div>
        </>
    )
}
